/** Night Shift design reminder: the office is a dense semi-3D escape machine—cold infrastructure, readable hazards, and valuable amber targets. */
import { Color3 } from "@babylonjs/core/Maths/math.color";
import { Vector3 } from "@babylonjs/core/Maths/math.vector";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder";
import type { Mesh } from "@babylonjs/core/Meshes/mesh";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { PointLight } from "@babylonjs/core/Lights/pointLight";
import type { Scene } from "@babylonjs/core/scene";
import type { SectorConfig } from "./sectors";
import { createProceduralLayout, type CoverNode, type OfficePickup, type ProceduralLayout } from "./ProceduralSector";
import type { Point2 } from "./types";

export interface EnergyShard { mesh: Mesh; innerRing: Mesh; outerRing: Mesh; position: Point2; collected: boolean; active: boolean; phase: number; }
export interface OfficeLoot { mesh: Mesh; halo: Mesh; data: OfficePickup; collected: boolean; }
interface MovingWallRuntime { mesh: Mesh; data: ProceduralLayout["movingWalls"][number]; }
interface SolidZone extends Point2 { width: number; depth: number; }
interface AnimatedProp { mesh: Mesh; kind: "window" | "monitor" | "door" | "sweep" | "trap" | "terminal"; phase: number; base: Vector3; }
interface DoorRuntime { mesh: Mesh; x: number; z: number; width: number; depth: number; open: boolean; horizontal: boolean; }
const MINT = new Color3(0.376, 0.965, 0.831); const NAVY = new Color3(0.008, 0.02, 0.055); const SLATE = new Color3(0.055, 0.1, 0.17); const VIOLET = new Color3(0.39, 0.38, 0.88); const AMBER = new Color3(0.94, 0.59, 0.2); const CORAL = new Color3(1, 0.32, 0.29); const HEAL = new Color3(0.22, 0.85, 0.72);

export class ReactorEnvironment {
  shards: EnergyShard[] = []; loot: OfficeLoot[] = []; readonly exitRelay: Mesh; private readonly exitRings: Mesh[] = []; private readonly dynamicMeshes: Mesh[] = []; private readonly cameraOccluders: Mesh[] = []; private readonly dynamicLights: PointLight[] = []; private readonly animatedProps: AnimatedProp[] = []; private doors: DoorRuntime[] = []; private movingWalls: MovingWallRuntime[] = []; private solidZones: SolidZone[] = []; private activeShardCount = 5; private exitPosition: Point2 = { x: 15.2, z: -9.2 }; private layout: ProceduralLayout | null = null; private seed = 1;
  constructor(private readonly scene: Scene) { this.createFloor(); this.createGrid(); this.createBoundary(); this.exitRelay = this.createExitRelay(); }
  configureSector(config: SectorConfig, seed: number) { this.seed = seed; this.activeShardCount = config.chargesRequired; this.layout = createProceduralLayout(config, seed); this.exitPosition = this.layout.exit; this.clearDynamic(); this.exitRelay.position.set(this.exitPosition.x, 0.02, this.exitPosition.z); this.exitRings.forEach((ring, index) => ring.position.set(this.exitPosition.x, 0.07 + index * 0.02, this.exitPosition.z)); this.layout.rooms.forEach((room, index) => { this.createOfficeRoom(room, index); this.createRoomLight(room, index); this.createSecuritySweep(room, index); }); this.layout.corridors.forEach((corridor, index) => this.createCorridor(corridor, index)); this.layout.platforms.forEach((platform, index) => this.createStair(platform, index)); this.layout.covers.forEach((cover, index) => this.createDesk(cover, index)); this.layout.movingWalls.forEach((wall, index) => this.createMovingWall(wall, index)); this.layout.traps.forEach((trap, index) => this.createTrap(trap, index)); this.layout.terminals.forEach((terminal, index) => this.createTerminal(terminal, index)); this.shards = this.layout.shards.map((position, index) => this.createShard(position, index)); this.loot = this.layout.pickups.map((pickup, index) => this.createLoot(pickup, index)); this.reset(); }
  get currentLayout() { return this.layout; } getSeed() { return this.seed; } isCovered(position: Point2) { return this.layout?.covers.some((cover) => inCover(position, cover)) ?? false; }
  getExit() { return this.exitPosition; }
  resolveMovement(from: Point2, wanted: Point2): Point2 {
    const dx = wanted.x - from.x; const dz = wanted.z - from.z;
    const steps = Math.max(1, Math.ceil(Math.hypot(dx, dz) / 0.14));
    let current = { ...from };
    for (let step = 1; step <= steps; step += 1) {
      const next = { x: from.x + dx * (step / steps), z: from.z + dz * (step / steps) };
      if (this.isOpen(next)) { current = next; continue; }
      const slideX = { x: next.x, z: current.z };
      const slideZ = { x: current.x, z: next.z };
      if (this.isOpen(slideX)) current = slideX;
      else if (this.isOpen(slideZ)) current = slideZ;
      else break;
    }
    return current;
  }
  blocksSight(from: Point2, to: Point2) { const covers = this.layout?.covers ?? []; for (let step = 0.07; step < 0.96; step += 0.07) { const point = { x: from.x + (to.x - from.x) * step, z: from.z + (to.z - from.z) * step }; if (covers.some((cover) => inCover(point, cover)) || this.solidZones.some((solid) => inSolid(point, solid, 0.04)) || this.movingWalls.some((wall) => inRuntimeWall(point, wall))) return true; } return false; }
  canInteract(position: Point2) { return Boolean(this.getNearbyTerminal(position) || this.getNearbyDoor(position)); } getNearbyTerminal(position: Point2) { return this.layout?.terminals.find((terminal) => Math.hypot(terminal.x - position.x, terminal.z - position.z) < 1.12) ?? null; }
  getNearbyDoor(position: Point2) { return this.doors.find((door) => !door.open && Math.hypot(door.x - position.x, door.z - position.z) < 1.45) ?? null; }
  openNearbyDoor(position: Point2) { const door = this.getNearbyDoor(position); if (!door) return false; door.open = true; (door.mesh.material as StandardMaterial).emissiveColor = MINT; door.mesh.setEnabled(false); return true; }
  isNearMovingWall(position: Point2) { return this.movingWalls.some((wall) => Math.hypot(wall.mesh.position.x - position.x, wall.mesh.position.z - position.z) < 1.85); }
  setLocalVision(_position: Point2, _tactical: boolean, _radius: number) {}
  setFirstPersonFocus(_position: Point2, enabled: boolean) { this.shards.forEach((shard) => { const visible = shard.active && !shard.collected && !enabled; shard.mesh.setEnabled(visible); shard.innerRing.setEnabled(visible); shard.outerRing.setEnabled(visible); }); this.loot.forEach((item) => { const visible = !item.collected && !enabled; item.mesh.setEnabled(visible); item.halo.setEnabled(visible); }); this.exitRelay.setEnabled(!enabled); this.exitRings.forEach((ring) => ring.setEnabled(!enabled)); this.dynamicMeshes.filter((mesh) => mesh.name.startsWith("office-light-fixture-")).forEach((mesh) => mesh.setEnabled(!enabled)); }
  reset() { this.shards.forEach((shard, index) => { shard.active = index < this.activeShardCount; shard.collected = !shard.active; shard.mesh.setEnabled(shard.active); shard.innerRing.setEnabled(shard.active); shard.outerRing.setEnabled(shard.active); }); this.loot.forEach((item) => { item.collected = false; item.mesh.setEnabled(true); item.halo.setEnabled(true); }); this.setExitActive(false); }
  update(elapsed: number) { this.shards.forEach((shard) => { if (shard.collected || !shard.active) return; const wave = Math.sin(elapsed * 2.1 + shard.phase); shard.mesh.position.y = 0.68 + wave * 0.1; shard.mesh.rotation.y = elapsed * 1.25 + shard.phase; shard.innerRing.scaling.setAll(1 + (wave + 1) * 0.07); shard.outerRing.scaling.setAll(1.05 + (wave + 1) * 0.13); }); this.loot.forEach((item, index) => { if (item.collected) return; item.mesh.position.y = 0.55 + Math.sin(elapsed * 2.4 + index) * 0.08; item.mesh.rotation.y = elapsed + index; }); this.exitRings.forEach((ring, index) => ring.rotation.y = elapsed * 0.52 * (index % 2 ? -1 : 1)); this.movingWalls.forEach((wall) => { const offset = Math.sin(elapsed * (Math.PI * 2 / wall.data.period)) * wall.data.travel * 0.5; wall.mesh.position[wall.data.axis] = wall.data[wall.data.axis] + offset; }); this.animatedProps.forEach((prop) => { const wave = Math.sin(elapsed * (prop.kind === "monitor" ? 3.4 : 1.55) + prop.phase); const material = prop.mesh.material as StandardMaterial; if (prop.kind === "window") { material.alpha = 0.34 + (wave + 1) * 0.18; prop.mesh.scaling.y = 0.94 + wave * 0.08; } else if (prop.kind === "monitor") { material.emissiveColor = new Color3(0.06, 0.62 + (wave + 1) * 0.15, 0.7 + (wave + 1) * 0.08); } else if (prop.kind === "door") { prop.mesh.position.y = prop.base.y + wave * 0.08; material.alpha = 0.7 + (wave + 1) * 0.1; } else if (prop.kind === "sweep") { prop.mesh.position.z = prop.base.z + wave * 0.9; } else if (prop.kind === "terminal") { prop.mesh.position.y = prop.base.y + wave * 0.08; prop.mesh.rotation.y = elapsed * 0.8 + prop.phase; } else { prop.mesh.rotation.y = elapsed * 1.8 + prop.phase; } }); }
  collectNearby(position: Point2, radius = 0.75) { let collected = 0; this.shards.forEach((shard) => { if (!shard.active || shard.collected || Math.hypot(shard.position.x - position.x, shard.position.z - position.z) > radius) return; shard.collected = true; shard.mesh.setEnabled(false); shard.innerRing.setEnabled(false); shard.outerRing.setEnabled(false); collected += 1; }); return collected; }
  collectLoot(position: Point2, radius = 0.8) { const collected: OfficePickup[] = []; this.loot.forEach((item) => { if (item.collected || Math.hypot(item.data.x - position.x, item.data.z - position.z) > radius) return; item.collected = true; item.mesh.setEnabled(false); item.halo.setEnabled(false); collected.push(item.data); }); return collected; }
  touchesTrap(position: Point2) { return this.layout?.traps.some((trap) => Math.hypot(trap.x - position.x, trap.z - position.z) < (trap.kind === "laser" ? 0.72 : 0.62)) ?? false; }
  atExit(position: Point2) { return Math.hypot(position.x - this.exitPosition.x, position.z - this.exitPosition.z) < 1.35; } setExitActive(active: boolean) { const color = active ? MINT : new Color3(0.12, 0.28, 0.33); this.exitRings.forEach((ring, index) => { const material = ring.material as StandardMaterial; material.emissiveColor = color; material.alpha = active ? 0.94 - index * 0.12 : 0.36; }); }
  private clearDynamic() { this.shards = []; this.loot = []; this.doors = []; this.movingWalls = []; this.solidZones = []; this.cameraOccluders.length = 0; this.animatedProps.length = 0; while (this.dynamicMeshes.length) this.dynamicMeshes.pop()?.dispose(); while (this.dynamicLights.length) this.dynamicLights.pop()?.dispose(); }
  private createFloor() { const floor = MeshBuilder.CreateGround("office-night-floor", { width: 42, height: 30 }, this.scene); const material = this.makeMaterial("office-night-floor-material", new Color3(0.055, 0.115, 0.17), 1); material.emissiveColor = new Color3(0.045, 0.085, 0.135); floor.material = material; }
  private createGrid() { const gridColor = new Color3(0.18, 0.48, 0.62); for (let x = -20; x <= 20; x += 2) { const line = MeshBuilder.CreateLines(`office-grid-x-${x}`, { points: [new Vector3(x, 0.012, -14.5), new Vector3(x, 0.012, 14.5)] }, this.scene); line.color = gridColor; line.alpha = x % 8 === 0 ? 0.19 : 0.065; } for (let z = -14; z <= 14; z += 2) { const line = MeshBuilder.CreateLines(`office-grid-z-${z}`, { points: [new Vector3(-20.5, 0.012, z), new Vector3(20.5, 0.012, z)] }, this.scene); line.color = gridColor; line.alpha = z % 8 === 0 ? 0.19 : 0.065; } }
  private createBoundary() { const railMaterial = this.makeMaterial("office-boundary-material", new Color3(0.12, 0.42, 0.49), 0.4); [{ width: 41.8, depth: 0.1, x: 0, z: -14.8 }, { width: 41.8, depth: 0.1, x: 0, z: 14.8 }, { width: 0.1, depth: 29.6, x: -20.8, z: 0 }, { width: 0.1, depth: 29.6, x: 20.8, z: 0 }].forEach((rail, index) => { const mesh = MeshBuilder.CreateBox(`office-boundary-${index}`, { width: rail.width, depth: rail.depth, height: 0.08 }, this.scene); mesh.position.set(rail.x, 0.07, rail.z); mesh.material = railMaterial; }); }
  private createOfficeRoom(room: ProceduralLayout["rooms"][number], index: number) {
    const roomTone = room.kind === "vault" ? new Color3(0.12, 0.075, 0.035) : room.kind === "relic" ? new Color3(0.07, 0.1, 0.2) : room.kind === "exit" ? new Color3(0.025, 0.16, 0.14) : new Color3(0.035, 0.11, 0.15);
    const slab = MeshBuilder.CreateBox(`office-room-slab-${index}`, { width: room.width, depth: room.depth, height: 0.11 }, this.scene); slab.position.set(room.x, 0.055, room.z); slab.material = this.makeMaterial(`office-room-material-${index}`, roomTone, 0.96); this.dynamicMeshes.push(slab);
    const wallMaterial = this.makeMaterial(`office-room-wall-material-${index}`, new Color3(0.14, 0.25, 0.31), 0.99);
    const doors = this.getDoorSides(index);
    this.createRoomSide(room, index, "north", doors.has("north"), wallMaterial);
    this.createRoomSide(room, index, "south", doors.has("south"), wallMaterial);
    this.createRoomSide(room, index, "west", doors.has("west"), wallMaterial);
    this.createRoomSide(room, index, "east", doors.has("east"), wallMaterial);
  }
  private createRoomLight(room: ProceduralLayout["rooms"][number], index: number) { const color = room.kind === "vault" ? AMBER : room.kind === "exit" ? MINT : new Color3(0.36, 0.68, 0.86); const fixture = MeshBuilder.CreateCylinder(`office-light-fixture-${index}`, { diameter: 0.3, height: 0.14, tessellation: 8 }, this.scene); fixture.position.set(room.x, 1.28, room.z); fixture.material = this.makeMaterial(`office-light-fixture-material-${index}`, color, 0.9); this.dynamicMeshes.push(fixture); const light = new PointLight(`office-room-light-${index}`, new Vector3(room.x, 1.15, room.z), this.scene); light.diffuse = color; light.intensity = room.kind === "entry" ? 1.6 : 1.05; light.range = 5.8; this.dynamicLights.push(light); this.animatedProps.push({ mesh: fixture, kind: "monitor", phase: index * 0.78, base: fixture.position.clone() }); }
  private createCorridor(corridor: ProceduralLayout["corridors"][number], index: number) {
    const slab = MeshBuilder.CreateBox(`office-corridor-slab-${index}`, { width: corridor.width, depth: corridor.depth, height: 0.09 }, this.scene); slab.position.set(corridor.x, 0.045, corridor.z); slab.material = this.makeMaterial(`office-corridor-material-${index}`, new Color3(0.025, 0.085, 0.12), 0.94); this.dynamicMeshes.push(slab);
    const wallMaterial = this.makeMaterial(`office-corridor-wall-material-${index}`, new Color3(0.11, 0.21, 0.27), 0.99);
    if (corridor.axis === "x") {
      this.createSolidBox(`office-corridor-north-${index}`, corridor.width, 0.18, corridor.x, corridor.z - corridor.depth / 2, wallMaterial);
      this.createSolidBox(`office-corridor-south-${index}`, corridor.width, 0.18, corridor.x, corridor.z + corridor.depth / 2, wallMaterial);
      this.createWindow(corridor.x + corridor.width * 0.16, corridor.z - corridor.depth / 2, true, index + 17);
    } else {
      this.createSolidBox(`office-corridor-west-${index}`, 0.18, corridor.depth, corridor.x - corridor.width / 2, corridor.z, wallMaterial);
      this.createSolidBox(`office-corridor-east-${index}`, 0.18, corridor.depth, corridor.x + corridor.width / 2, corridor.z, wallMaterial);
      this.createWindow(corridor.x - corridor.width / 2, corridor.z + corridor.depth * 0.16, false, index + 17);
    }
  }
  private getDoorSides(index: number) {
    const room = this.layout?.rooms[index]; const doors = new Set<"north" | "south" | "west" | "east">();
    if (!room || !this.layout) return doors;
    this.layout.connections.filter((connection) => connection.from === index || connection.to === index).forEach((connection) => {
      const other = this.layout!.rooms[connection.from === index ? connection.to : connection.from]; const dx = other.x - room.x; const dz = other.z - room.z;
      if (Math.abs(dx) > Math.abs(dz)) doors.add(dx > 0 ? "east" : "west"); else doors.add(dz > 0 ? "south" : "north");
    });
    return doors;
  }
  private createRoomSide(room: ProceduralLayout["rooms"][number], index: number, side: "north" | "south" | "west" | "east", hasDoor: boolean, material: StandardMaterial) {
    const horizontal = side === "north" || side === "south"; const sign = side === "north" || side === "west" ? -1 : 1; const length = horizontal ? room.width : room.depth; const doorWidth = 2.18;
    const createSegment = (segmentLength: number, offset: number) => {
      if (segmentLength <= 0.1) return;
      const x = horizontal ? room.x + offset : room.x + sign * room.width / 2; const z = horizontal ? room.z + sign * room.depth / 2 : room.z + offset;
      this.createSolidBox(`office-wall-${index}-${side}-${offset}`, horizontal ? segmentLength : 0.2, horizontal ? 0.2 : segmentLength, x, z, material);
    };
    if (hasDoor) {
      const segment = (length - doorWidth) / 2; createSegment(segment, -(doorWidth / 2 + segment / 2)); createSegment(segment, doorWidth / 2 + segment / 2);
      this.createDoorFrame(room, index, side, doorWidth);
    } else { createSegment(length, 0); this.createWindow(horizontal ? room.x + (index % 2 ? -0.65 : 0.65) : room.x + sign * room.width / 2, horizontal ? room.z + sign * room.depth / 2 : room.z + (index % 2 ? -0.65 : 0.65), horizontal, index); }
  }
  private createSolidBox(name: string, width: number, depth: number, x: number, z: number, material: StandardMaterial) { const mesh = MeshBuilder.CreateBox(name, { width, depth, height: 1.34 }, this.scene); mesh.position.set(x, 0.67, z); mesh.material = material; this.dynamicMeshes.push(mesh); this.cameraOccluders.push(mesh); this.solidZones.push({ x, z, width, depth }); }
  private createDoorFrame(room: ProceduralLayout["rooms"][number], index: number, side: "north" | "south" | "west" | "east", doorWidth: number) {
    const horizontal = side === "north" || side === "south"; const sign = side === "north" || side === "west" ? -1 : 1; const x = horizontal ? room.x : room.x + sign * room.width / 2; const z = horizontal ? room.z + sign * room.depth / 2 : room.z;
    const frameMaterial = this.makeMaterial(`office-door-material-${index}-${side}`, new Color3(0.18, 0.62, 0.66), 0.78);
    const lintel = MeshBuilder.CreateBox(`office-door-lintel-${index}-${side}`, { width: horizontal ? doorWidth : 0.18, depth: horizontal ? 0.18 : doorWidth, height: 0.16 }, this.scene); lintel.position.set(x, 1.28, z); lintel.material = frameMaterial; this.dynamicMeshes.push(lintel);
    const optionalDoor = index >= 9; const panel = MeshBuilder.CreateBox(`office-door-panel-${index}-${side}`, { width: horizontal ? doorWidth * 0.82 : 0.12, depth: horizontal ? 0.12 : doorWidth * 0.82, height: 1.12 }, this.scene); panel.position.set(x, 0.56, z); panel.material = frameMaterial; panel.setEnabled(optionalDoor); this.dynamicMeshes.push(panel); this.doors.push({ mesh: panel, x, z, width: horizontal ? doorWidth * 0.82 : 0.12, depth: horizontal ? 0.12 : doorWidth * 0.82, open: !optionalDoor, horizontal }); this.animatedProps.push({ mesh: panel, kind: "door", phase: index * 0.7, base: panel.position.clone() });
  }
  private createWindow(x: number, z: number, horizontal: boolean, phase: number) { const pane = MeshBuilder.CreateBox(`office-window-${phase}`, { width: horizontal ? 1.1 : 0.05, depth: horizontal ? 0.05 : 1.1, height: 0.64 }, this.scene); pane.position.set(x, 0.78, z); pane.material = this.makeMaterial(`office-window-material-${phase}`, new Color3(0.08, 0.62, 0.74), 0.5); this.dynamicMeshes.push(pane); this.animatedProps.push({ mesh: pane, kind: "window", phase, base: pane.position.clone() }); }
  private createSecuritySweep(room: ProceduralLayout["rooms"][number], index: number) { if (room.kind !== "entry") return; const beam = MeshBuilder.CreateBox(`office-security-sweep-${index}`, { width: room.width * 0.74, depth: 0.07, height: 0.05 }, this.scene); beam.position.set(room.x, 0.12, room.z - room.depth * 0.23); beam.material = this.makeMaterial(`office-security-sweep-material-${index}`, CORAL, 0.98); this.dynamicMeshes.push(beam); this.animatedProps.push({ mesh: beam, kind: "sweep", phase: index, base: beam.position.clone() }); const field = MeshBuilder.CreateDisc(`office-security-field-${index}`, { radius: 2.05, tessellation: 3 }, this.scene); field.rotation.x = Math.PI / 2; field.rotation.z = Math.PI * 0.5; field.position.set(room.x + 0.2, 0.03, room.z - room.depth * 0.04); field.material = this.makeMaterial(`office-security-field-material-${index}`, CORAL, 0.24); this.dynamicMeshes.push(field); this.animatedProps.push({ mesh: field, kind: "trap", phase: index + 0.45, base: field.position.clone() }); const emitter = MeshBuilder.CreateCylinder(`office-security-emitter-${index}`, { diameter: 0.34, height: 0.32, tessellation: 6 }, this.scene); emitter.position.set(room.x + room.width * 0.34, 0.17, room.z - room.depth * 0.23); emitter.material = this.makeMaterial(`office-security-emitter-material-${index}`, CORAL, 0.98); this.dynamicMeshes.push(emitter); }
  private createStair(platform: { x: number; z: number; width: number; depth: number; height: number }, index: number) { for (let step = 0; step < 3; step += 1) { const stair = MeshBuilder.CreateBox(`office-stair-${index}-${step}`, { width: platform.width, depth: platform.depth / 3 + 0.03, height: platform.height * ((step + 1) / 3) }, this.scene); stair.position.set(platform.x, stair.getBoundingInfo().boundingBox.extendSize.y, platform.z - platform.depth / 2 + (step + 0.5) * platform.depth / 3); stair.material = this.makeMaterial(`office-stair-material-${index}-${step}`, new Color3(0.35, 0.42, 0.47), 0.88); this.dynamicMeshes.push(stair); this.cameraOccluders.push(stair); } }
  private createDesk(cover: CoverNode, index: number) { const desk = MeshBuilder.CreateBox(`office-desk-${index}`, { width: cover.width, depth: cover.depth, height: 0.64 }, this.scene); desk.position.set(cover.x, 0.33, cover.z); desk.material = this.makeMaterial(`office-desk-material-${index}`, new Color3(0.045, 0.18, 0.23), 0.94); this.dynamicMeshes.push(desk); this.cameraOccluders.push(desk); this.solidZones.push({ x: cover.x, z: cover.z, width: cover.width, depth: cover.depth }); const screen = MeshBuilder.CreateBox(`office-desk-screen-${index}`, { width: cover.width * 0.28, depth: 0.04, height: 0.26 }, this.scene); screen.position.set(cover.x, 0.7, cover.z - cover.depth * 0.23); screen.material = this.makeMaterial(`office-desk-screen-material-${index}`, new Color3(0.08, 0.63, 0.68), 0.78); this.dynamicMeshes.push(screen); this.cameraOccluders.push(screen); this.animatedProps.push({ mesh: screen, kind: "monitor", phase: index * 0.62, base: screen.position.clone() }); }
  private createMovingWall(wall: ProceduralLayout["movingWalls"][number], index: number) { const mesh = MeshBuilder.CreateBox(`moving-company-wall-${index}`, { width: wall.width, depth: wall.depth, height: 1.28 }, this.scene); mesh.position.set(wall.x, 0.64, wall.z); mesh.material = this.makeMaterial(`moving-company-wall-material-${index}`, new Color3(0.62, 0.08, 0.06), 0.95); this.dynamicMeshes.push(mesh); this.movingWalls.push({ mesh, data: wall }); }
  private createTrap(trap: ProceduralLayout["traps"][number], index: number) { const color = trap.kind === "laser" ? CORAL : AMBER; const disc = MeshBuilder.CreateDisc(`office-trap-${index}`, { radius: trap.kind === "laser" ? 0.75 : 0.58, tessellation: 4 }, this.scene); disc.rotation.x = Math.PI / 2; disc.position.set(trap.x, 0.025, trap.z); disc.material = this.makeMaterial(`office-trap-material-${index}`, color, 0.45); this.dynamicMeshes.push(disc); const emitter = MeshBuilder.CreateCylinder(`office-trap-emitter-${index}`, { diameter: 0.28, height: 0.36, tessellation: 6 }, this.scene); emitter.position.set(trap.x, 0.18, trap.z); emitter.material = this.makeMaterial(`office-trap-emitter-material-${index}`, color, 0.78); this.dynamicMeshes.push(emitter); this.animatedProps.push({ mesh: emitter, kind: "trap", phase: index * 0.7, base: emitter.position.clone() }); }
  private createTerminal(terminal: { x: number; z: number; kind: "story" | "roulette" }, index: number) { const color = terminal.kind === "roulette" ? AMBER : VIOLET; const node = MeshBuilder.CreateCylinder(`office-terminal-${terminal.kind}-${index}`, { diameter: 0.64, height: 1.15, tessellation: 6 }, this.scene); node.position.set(terminal.x, 0.58, terminal.z); node.material = this.makeMaterial(`office-terminal-material-${index}`, color, 0.9); this.dynamicMeshes.push(node); this.animatedProps.push({ mesh: node, kind: "terminal", phase: index * 1.1, base: node.position.clone() }); }
  private createShard(position: Point2, index: number): EnergyShard { const shard = MeshBuilder.CreateBox(`office-access-key-${index}`, { size: 0.46 }, this.scene); shard.position.set(position.x, 0.68, position.z); shard.rotation.set(Math.PI / 4, Math.PI / 4, 0); shard.material = this.makeMaterial(`office-access-key-material-${index}`, MINT, 1); const innerRing = MeshBuilder.CreateTorus(`office-access-ring-${index}`, { diameter: 0.84, thickness: 0.026, tessellation: 32 }, this.scene); innerRing.position.set(position.x, 0.05, position.z); innerRing.material = this.makeMaterial(`office-access-ring-material-${index}`, MINT, 0.9); const outerRing = MeshBuilder.CreateTorus(`office-access-ring-outer-${index}`, { diameter: 1.3, thickness: 0.016, tessellation: 32 }, this.scene); outerRing.position.set(position.x, 0.035, position.z); outerRing.material = this.makeMaterial(`office-access-ring-outer-material-${index}`, MINT, 0.58); this.dynamicMeshes.push(shard, innerRing, outerRing); return { mesh: shard, innerRing, outerRing, position, collected: false, active: true, phase: index * 0.8 }; }
  private createLoot(data: OfficePickup, index: number): OfficeLoot { const color = data.kind === "cash" || data.kind === "relic" ? AMBER : data.kind === "heal" ? HEAL : new Color3(0.25, 0.6, 1); const mesh = data.kind === "relic" ? MeshBuilder.CreateTorus(`office-loot-${index}`, { diameter: 0.55, thickness: 0.1, tessellation: 24 }, this.scene) : MeshBuilder.CreateBox(`office-loot-${index}`, { size: data.kind === "cash" ? 0.42 : 0.5 }, this.scene); mesh.position.set(data.x, 0.55, data.z); mesh.material = this.makeMaterial(`office-loot-material-${index}`, color, 1); const halo = MeshBuilder.CreateTorus(`office-loot-halo-${index}`, { diameter: 0.9, thickness: 0.022, tessellation: 28 }, this.scene); halo.position.set(data.x, 0.04, data.z); halo.material = this.makeMaterial(`office-loot-halo-material-${index}`, color, 0.62); this.dynamicMeshes.push(mesh, halo); return { mesh, halo, data, collected: false }; }
  private createExitRelay() { const anchor = MeshBuilder.CreateBox("office-fire-exit-anchor", { size: 0.01 }, this.scene); const diameters = [2.45, 1.78, 1.08]; diameters.forEach((diameter, index) => { const ring = MeshBuilder.CreateTorus(`office-fire-exit-ring-${index}`, { diameter, thickness: 0.058, tessellation: 42 }, this.scene); ring.material = this.makeMaterial(`office-fire-exit-material-${index}`, new Color3(0.12, 0.28, 0.33), 0.36); this.exitRings.push(ring); }); return anchor; }
  setCameraOcclusion(position: Point2, active: boolean) { this.cameraOccluders.forEach((mesh) => { const distance = Math.hypot(mesh.position.x - position.x, mesh.position.z - position.z); mesh.visibility = active && distance < 3.45 ? Math.max(0.12, distance / 3.45) : 1; }); }
  private isOpen(position: Point2) { if (position.x < -20 || position.x > 20 || position.z < -14 || position.z > 14) return false; const radius = 0.42; if (this.solidZones.some((solid) => Math.abs(position.x - solid.x) < solid.width / 2 + radius && Math.abs(position.z - solid.z) < solid.depth / 2 + radius)) return false; if (this.doors.some((door) => !door.open && Math.abs(position.x - door.x) < door.width / 2 + radius && Math.abs(position.z - door.z) < door.depth / 2 + radius)) return false; return !this.movingWalls.some((wall) => inRuntimeWall(position, wall)); }
  private makeMaterial(name: string, color: Color3, alpha: number) { const material = new StandardMaterial(name, this.scene); material.diffuseColor = color; material.emissiveColor = color.scale(0.3); material.specularColor = new Color3(0.28, 0.34, 0.4); material.alpha = alpha; material.disableLighting = false; material.backFaceCulling = false; return material; }
}
function inCover(point: Point2, cover: CoverNode) { return Math.abs(point.x - cover.x) <= cover.width / 2 + 0.12 && Math.abs(point.z - cover.z) <= cover.depth / 2 + 0.12; }
function inSolid(point: Point2, solid: SolidZone, padding = 0) { return Math.abs(point.x - solid.x) <= solid.width / 2 + padding && Math.abs(point.z - solid.z) <= solid.depth / 2 + padding; }
function inRuntimeWall(point: Point2, wall: MovingWallRuntime) { const size = wall.mesh.getBoundingInfo().boundingBox.extendSize; return Math.abs(point.x - wall.mesh.position.x) <= size.x + 0.1 && Math.abs(point.z - wall.mesh.position.z) <= size.z + 0.1; }
